# Rockchip 平台 Rootfs 构建 — base + customize 两阶段

load("//build:rootfs_base.bzl", "rootfs_base")
load("//build:rootfs_customize.bzl", "rootfs_customize")

rootfs_base(
    name = "base",
    build_script = "build_base.sh",
    packages = select({
        "//build:board_radxa_zero3w": [
            "systemd",
            "systemd-sysv",
            "dbus",
            "network-manager",
            "iputils-ping",
            "iproute2",
            "openssh-server",
            "sudo",
            "bash",
            "ca-certificates",
            "locales",
        ],
    }),
    rootfs_src = select({
        "//build:board_radxa_zero3w": "@rootfs_src_radxa_zero3w//:ubuntu-base.tar.gz",
    }),
)

rootfs_customize(
    name = "rockchip",
    base = ":base",
    build_script = "build_customize.sh",
    custom_packages = select({
        "//build:board_radxa_zero3w": [],
    }),
    custom_packages_dir = "//packages:all_debs",
    overlay = select({
        "//build:board_radxa_zero3w": "//board/radxa-zero3w:overlay",
    }),
    visibility = ["//visibility:public"],
)
