app:
  name: radxa-firmware-sc8280xp
  version: 0.2.41-1flange1
  description: Radxa SC8280XP 补充固件与 DSP runtime
  type: vendor
  arch: [aarch64]

maintainer:
  name: flange
  email: flange@localhost

build:
  system: none
