# Rockchip 平台内核构建

load("//build:kernel_build.bzl", "kernel_build")

filegroup(
    name = "patches",
    srcs = glob(["patches/**/*.patch"], allow_empty = True),
    visibility = ["//visibility:public"],
)

kernel_build(
    name = "rockchip",
    build_script = "build.sh",
    kernel_src = select({
        "//build:board_radxa_zero3w": "@kernel_src_radxa_zero3w//:src",
        "//build:board_neons_core3566_nanob": "@kernel_src_neons_core3566_nanob//:src",
        "//build:board_tspi_rk3566": "@kernel_src_tspi_rk3566//:src",
    }),
    defconfig = select({
        "//build:board_radxa_zero3w": "rockchip_linux_defconfig",
        "//build:board_neons_core3566_nanob": "rockchip_linux_defconfig",
        "//build:board_tspi_rk3566": "rockchip_linux_defconfig",
    }),
    dts = select({
        "//build:board_radxa_zero3w": "rk3566-radxa-zero-3w-aic8800d80",
        "//build:board_neons_core3566_nanob": "rk3566-neons-core-wavesharecm4-nano-b",
        "//build:board_tspi_rk3566": "tspi-rk3566-user-v10-ext39-linux",
    }),
    dts_dir = "rockchip",
    jobs = 0,
    platform_patches = [":patches"],
    board_patches = select({
        "//build:board_radxa_zero3w": ["//board/radxa-zero3w:kernel_patches"],
        "//build:board_neons_core3566_nanob": ["//board/neons-core3566-nanob:kernel_patches"],
        "//build:board_tspi_rk3566": ["//board/tspi-rk3566:kernel_patches"],
    }),
    visibility = ["//visibility:public"],
)
