#!/bin/sh -e
#
# Usage:
# usbdevice [start|update|stop]
#
# Hookable stages:
# usb_<pre|post>_<init|prepare|start|stop|restart>_hook
# <usb function>_<pre|post>_<prepare|start|stop>_hook
#
# Example hook:
# root@RK3588:/# more /etc/usbdevice.d/usb_init.sh
# #!/bin/sh
# usb_pre_init_hook()
# {
#	echo "usb pre-init hook"
# }
#
# root@RK3588:/# more /etc/usbdevice.d/uvc.sh
# #!/bin/sh
# UVC_INSTANCES="uvc.gs1 uvc.gs2"

# Uncomment below to see more logs
# set -x

# Load default env variables from profiles
. /etc/profile

LOG_FILE=/tmp/usbdevice.log
USB_FUNCS_FILE=/tmp/.usbdevice

alias usb_enable='touch $USB_FUNCS_FILE'
alias usb_disable='rm -f $USB_FUNCS_FILE'
alias usb_is_enabled='[ -f $USB_FUNCS_FILE ]'
alias usb_set_started='echo $USB_FUNCS > $USB_FUNCS_FILE'
usb_get_started()
{
	usb_is_enabled || return 0
	cat $USB_FUNCS_FILE
}

CONFIGFS_DIR=/sys/kernel/config

# 从配置文件加载平台参数（板级 overlay 覆盖 App 默认值）
USB_CONF_FILE=/etc/usbdevice.conf
[ -r "$USB_CONF_FILE" ] && . "$USB_CONF_FILE"

# 配置文件未指定时的 fallback 默认值
USB_GROUP=${USB_GROUP:-linux}
USB_VENDOR_ID=${USB_VENDOR_ID:-0x1d6b}
USB_PRODUCT_NAME=${USB_PRODUCT_NAME:-linux-gadget}
USB_MANUFACTURER=${USB_MANUFACTURER:-linux}
USB_SERIAL_SOURCE=${USB_SERIAL_SOURCE:-cpuinfo}
USB_BCD_DEVICE=${USB_BCD_DEVICE:-0x0310}
USB_BCD_USB=${USB_BCD_USB:-0x0200}
USB_MAX_POWER=${USB_MAX_POWER:-500}
USB_PID_DEFAULT=${USB_PID_DEFAULT:-0x0019}

USB_STRINGS_ATTR=strings/0x409
USB_GADGET_DIR=$CONFIGFS_DIR/usb_gadget/$USB_GROUP
USB_GADGET_STRINGS_DIR=$USB_GADGET_DIR/$USB_STRINGS_ATTR
USB_FUNCTIONS_DIR=$USB_GADGET_DIR/functions
USB_CONFIGS_DIR=$USB_GADGET_DIR/configs/b.1
USB_CONFIGS_STRINGS_DIR=$USB_CONFIGS_DIR/$USB_STRINGS_ATTR

# Make sure that we own this session (pid equals sid)
if ! ps x -o pid,sid | grep -wq "$$$"; then
	setsid $0 $@
	exit $?
fi

# ---- helper functions
usb_msg()
{
	logger -t "$(basename "$0")" "[$$]: $@"
	echo "[$(date +"%F %T")] $@"
}

usb_pid()
{
	# 按字母排序、下划线连接，查找 USB_PID_<key> 配置变量
	USB_PID_KEY="USB_PID_$(echo $USB_FUNCS | xargs -n 1 | sort | paste -sd'_')"
	eval USB_PID_VAL="\${$USB_PID_KEY}"
	echo ${USB_PID_VAL:-$USB_PID_DEFAULT}
}

usb_instances()
{
	for func in $@; do
		VAR=$(echo $func | tr 'a-z' 'A-Z')_INSTANCES
		eval echo "\${$VAR:-$func.gs0}"
	done
}

usb_run_stage()
{
	for f in $1_pre_$2_hook $1_$2 $1_post_$2_hook; do
		type $f >/dev/null 2>/dev/null || continue

		usb_msg "Run stage: $f"
		eval $f || break
	done
}

usb_wait_files()
{
	# 等待 adbd 真正打开 ep1 文件描述符
	# 注意：ep1 inode 在 FFS 挂载后永久存在，不能用 [ -e ] 判断
	for i in $(seq 200); do
		ADBD_PID=$(pidof adbd 2>/dev/null) || true
		if [ -n "$ADBD_PID" ] && \
		   ls -la /proc/$ADBD_PID/fd/ 2>/dev/null | grep -q "usb-ffs/adb/ep1"; then
			break
		fi
		sleep .01
	done
}

usb_release_files()
{
	for i in `seq 200`;do
		fuser -s -k $@ 2>/dev/null || break
		sleep .01
	done
}

# 等待 UDC gadget state 达到目标值（$1=目标 state, $2=最多重试次数 ×0.1s，默认 30=3s）
usb_wait_state()
{
	UDC_STATE_FILE=/sys/class/udc/$USB_UDC/state
	for i in $(seq ${2:-30}); do
		[ "$(cat $UDC_STATE_FILE 2>/dev/null)" = "$1" ] && return 0
		sleep .1
	done
	return 1
}

# 用 soft_connect 纯翻转 D+ 上拉（disconnect→connect），强制主机重新枚举。
# 不动 ConfigFS symlink / FFS，因此不会触发 functionfs_unbind 破坏 adbd 持有的
# ep fd（参见 usb_prepare 里"UDC unbound"分支的注释）——比 stop+start 安全。
usb_bounce_connection()
{
	SC=/sys/class/udc/$USB_UDC/soft_connect
	[ -w "$SC" ] || { usb_msg "[DEBUG bounce] 无 soft_connect ($SC)，跳过"; return 1; }
	usb_msg "[DEBUG bounce] soft_connect disconnect -> connect"
	echo disconnect > "$SC" 2>/dev/null || return 1
	sleep .3
	echo connect > "$SC" 2>/dev/null || return 1
	return 0
}

# usage: usb_mount <src> <mountpoint> <options>
usb_mount()
{
	mkdir -p $2
	mountpoint -q $2 || mount $@
}

usb_umount()
{
	mountpoint -q $1 || return 0
	usb_release_files -m $1
	umount $1
}

usb_symlink()
{
	mkdir -p $1
	[ -e $2 ] || ln -s $1 $2
}

usb_try_symlink()
{
	usb_symlink $@ &>/dev/null || true
}

usb_write()
{
	if echo "x$1" | grep -q "^x-"; then
		OPTS=$1
		shift
	fi

	FILE=$1
	shift

	if [ -r $FILE ] && [ "$(cat $FILE)" = "$@" ]; then
		return 0
	fi

	echo $OPTS "$@" > $FILE
}

usb_try_write()
{
	usb_write $@ &>/dev/null || true
}

usb_start_daemon()
{
	NAME=$(echo $1 | sed "s#^[^ ]*/\([^ ]*\).*#\1#")
	TAG_FILE=/tmp/.usb_$NAME

	# Enable spawn
	touch $TAG_FILE

	# Already started
	DAEMON_STARTED="$(usb_get_started)"
	if [ -n "$DAEMON_STARTED" ]; then
		usb_msg "[DEBUG usb_start_daemon] usb_get_started=$DAEMON_STARTED, skipping daemon launch for $1"
		return 0
	fi
	usb_msg "[DEBUG usb_start_daemon] launching daemon: $1"

	# Start and spawn background daemon
	{
		exec 3<&-

		cd /
		while usb_is_enabled; do
			# Don't spawn after stopped
			[ ! -f $TAG_FILE ] ||
				start-stop-daemon -Sqx $@ || true
			sleep .5
		done
	}&
}

usb_stop_daemon()
{
	NAME=$(echo $1 | sed "s#^[^ ]*/\([^ ]*\).*#\1#")
	TAG_FILE=/tmp/.usb_$NAME

	# Stop and disable spawn
	rm -f $TAG_FILE
	start-stop-daemon -Kqox $@
}

usb_load_config()
{
	USB_CONFIG_FILE=$(find /etc/ -name .usb_config | head -n 1)
	[ -n "$USB_CONFIG_FILE" -a -r "$USB_CONFIG_FILE" ] || return 0

	ums_parse()
	{
		grep "\<$1=" "$USB_CONFIG_FILE" | cut -d'=' -f2
	}
	UMS_FILE="$(ums_parse ums_block)"
	UMS_SIZE=$(ums_parse ums_block_size || echo 0)M
	UMS_FSTYPE=$(ums_parse ums_block_type)
	UMS_MOUNT=$([ "$(ums_parse ums_block_auto_mount)" != on ]; echo $?)
	UMS_RO=$([ "$(ums_parse ums_block_ro)" != on ]; echo $?)

	USB_FUNCS="$(sed -n "s/usb_\(.*\)_en/\1/p" "$USB_CONFIG_FILE" | xargs)"
}

# ---- adb
ADB_INSTANCES=${ADB_INSTANCES:-ffs.adb}

adb_prepare()
{
	usb_mount adb /dev/usb-ffs/adb -o uid=2000,gid=2000,no_disconnect=1 -t functionfs
	ADBD_PID="$(pidof adbd 2>/dev/null || echo '')"
	usb_msg "[DEBUG adb_prepare] adbd pid=$ADBD_PID ffs_users=$(fuser -m /dev/usb-ffs/adb 2>&1 || echo 'none')"
	usb_start_daemon /usr/bin/adbd
	usb_wait_files -m /dev/usb-ffs/adb
	ADBD_PID_AFTER="$(pidof adbd 2>/dev/null || echo '')"
	usb_msg "[DEBUG adb_prepare] after: adbd pid=$ADBD_PID_AFTER"
}

adb_stop()
{
	usb_stop_daemon /usr/bin/adbd
}

# ---- ntb
NTB_INSTANCES=${NTB_INSTANCES:-ffs.ntb}

ntb_prepare()
{
	usb_mount ntb /dev/usb-ffs/ntb -o uid=2000,gid=2000 -t functionfs
}

# ---- uac1
uac1_prepare()
{
	for f in $(find . -name "*_feature_unit"); do
		echo 1 >$f
	done
}

# ---- uac2
uac2_prepare()
{
	uac1_prepare
}

# ---- mtp
mtp_prepare()
{
	echo "MTP" > os_desc/interface.MTP/compatible_id
	echo 1 > $USB_GADGET_DIR/os_desc/use
}

mtp_start()
{
	usb_start_daemon /usr/bin/mtp-server
	usb_wait_files /dev/mtp_usb
}

mtp_stop()
{
	usb_stop_daemon /usr/bin/mtp-server
	usb_release_files /dev/mtp_usb

	echo 0 > $USB_GADGET_DIR/os_desc/use
}

# ---- acm
ACM_INSTANCES=${ACM_INSTANCES:-acm.gs6}

# ---- rndis
# Nothing special

# ---- uvc
UVC_INSTANCES=${UVC_INSTANCES:-uvc.gs6}

uvc_add_yuyv()
{
	WIDTH=$(echo $1 | cut -d'x' -f1)
	HEIGHT=$(echo $1 | cut -d'x' -f2)
	DIR=${HEIGHT}p

	[ ! -d $DIR ] || return 0

	mkdir -p $DIR
	echo $WIDTH > $DIR/wWidth
	echo $HEIGHT > $DIR/wHeight
	echo 333333 > $DIR/dwDefaultFrameInterval
	echo $((WIDTH * HEIGHT * 20)) > $DIR/dwMinBitRate
	echo $((WIDTH * HEIGHT * 20)) > $DIR/dwMaxBitRate
	echo $((WIDTH * HEIGHT * 2)) > $DIR/dwMaxVideoFrameBufferSize
	echo -e "333333\n666666\n1000000\n2000000" > $DIR/dwFrameInterval
}

uvc_add_mjpeg()
{
	WIDTH=$(echo $1 | cut -d'x' -f1)
	HEIGHT=$(echo $1 | cut -d'x' -f2)
	DIR=${HEIGHT}p

	[ ! -d $DIR ] || return 0

	mkdir -p $DIR
	echo $WIDTH > $DIR/wWidth
	echo $HEIGHT > $DIR/wHeight
	echo 333333 > $DIR/dwDefaultFrameInterval
	echo $((WIDTH * HEIGHT * 20)) > $DIR/dwMinBitRate
	echo $((WIDTH * HEIGHT * 20)) > $DIR/dwMaxBitRate
	echo $((WIDTH * HEIGHT * 2)) > $DIR/dwMaxVideoFrameBufferSize
	echo -e "333333\n666666\n1000000\n2000000" > $DIR/dwFrameInterval
}

uvc_add_h264()
{
	WIDTH=$(echo $1 | cut -d'x' -f1)
	HEIGHT=$(echo $1 | cut -d'x' -f2)
	DIR=${HEIGHT}p

	[ ! -d $DIR ] || return 0

	mkdir -p $DIR
	echo $WIDTH > $DIR/wWidth
	echo $HEIGHT > $DIR/wHeight
	echo 333333 > $DIR/dwDefaultFrameInterval
	echo $((WIDTH * HEIGHT * 10)) > $DIR/dwMinBitRate
	echo $((WIDTH * HEIGHT * 10)) > $DIR/dwMaxBitRate
	echo -e "333333\n666666\n1000000\n2000000" > $DIR/dwFrameInterval
}

uvc_support_resolutions()
{
	case ${1:-yuyv} in
		yuyv)	echo "640x480 1280x720";;
		mjpeg)	echo "640x480 1280x720 1920x1080 2560x1440 2592x1944";;
		h264)	echo "640x480 1280x720 1920x1080";;
	esac
}

uvc_prepare()
{
	UVC_DIR=$(pwd)

	usb_symlink $UVC_DIR/control/header/h $UVC_DIR/control/class/fs/h
	usb_symlink $UVC_DIR/control/header/h $UVC_DIR/control/class/ss/h

	usb_symlink $UVC_DIR/streaming/header/h $UVC_DIR/streaming/class/fs/h
	usb_symlink $UVC_DIR/streaming/header/h $UVC_DIR/streaming/class/hs/h
	usb_symlink $UVC_DIR/streaming/header/h $UVC_DIR/streaming/class/ss/h

	UVC_YUYV_RES=$(uvc_support_resolutions yuyv)
	if [ -n "$UVC_YUYV_RES" ]; then
		usb_try_symlink $UVC_DIR/streaming/uncompressed/u \
			$UVC_DIR/streaming/header/h/u
		cd $UVC_DIR/streaming/uncompressed/u

		for res in $UVC_YUYV_RES; do
			uvc_add_yuyv $res
		done
	fi

	UVC_MJPEG_RES=$(uvc_support_resolutions mjpeg)
	if [ -n "$UVC_MJPEG_RES" ]; then
		usb_try_symlink $UVC_DIR/streaming/mjpeg/m \
			$UVC_DIR/streaming/header/h/m
		cd $UVC_DIR/streaming/mjpeg/m

		for res in $UVC_MJPEG_RES; do
			uvc_add_mjpeg $res
		done
	fi

	UVC_H264_RES=$(uvc_support_resolutions h264)
	if [ -n "$UVC_H264_RES" ]; then
		usb_try_symlink $UVC_DIR/streaming/framebased/f \
			$UVC_DIR/streaming/header/h/f
		cd $UVC_DIR/streaming/framebased/f

		for res in $UVC_H264_RES; do
			uvc_add_h264 $res
		done

		usb_try_write -ne guidFormat "\\x48\\x32\\x36\\x34\\x00\\x00\\x10\\x00\\x80\\x00\\x00\\xaa\\x00\\x38\\x9b\\x71"
	fi
}

# TODO: Start UVC daemon in uvc_start
# TODO: Stop UVC daemon in uvc_stop

# ---- hid
HID_INSTANCES=${HID_INSTANCES:-hid.usb0}

hid_prepare()
{
	echo 1 > protocol
	echo 1 > subclass
	echo 8 > report_length
	echo -ne "\\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0" \
		> report_desc
}

# ---- ums
UMS_INSTANCES=${UMS_INSTANCES:-mass_storage.0}

ums_prepare()
{
	if [ ! -f "$UMS_FILE" ]; then
		usb_msg "Formating $UMS_FILE($UMS_SIZE) to $UMS_FSTYPE"
		truncate -s $UMS_SIZE "$UMS_FILE"
		mkfs.$UMS_FSTYPE "$UMS_FILE" || \
			usb_msg "Failed to format $UMS_FILE to $UMS_FSTYPE"
	fi
}

ums_stop()
{
	echo > lun.0/file
	usb_umount "$UMS_MOUNTPOINT"

	[ "$UMS_MOUNT" -eq 1 ] || return 0

	# Try auto fstype firstly
	usb_mount "$UMS_FILE" "$UMS_MOUNTPOINT" -o sync 2>/dev/null || \
		usb_mount "$UMS_FILE" "$UMS_MOUNTPOINT" -o sync -t $UMS_FSTYPE
}

ums_start()
{
	case "$USB_STATE" in
		CONFIGURED)
			if [ "$(cat lun.0/ro)" != "$UMS_RO" ]; then
				echo > lun.0/file
				echo $UMS_RO > lun.0/ro
			fi

			if ! grep -wq "$UMS_FILE" lun.0/file; then
				usb_umount "$UMS_MOUNTPOINT"
				echo "$UMS_FILE" > lun.0/file
			fi
			;;
		DISCONNECTED)
			ums_stop
			;;
	esac
}

# ---- global
usb_init()
{
	usb_msg "Initializing"

	echo $USB_VENDOR_ID > idVendor
	echo $USB_BCD_DEVICE > bcdDevice
	echo $USB_BCD_USB > bcdUSB

	mkdir -p $USB_GADGET_STRINGS_DIR

	case "$USB_SERIAL_SOURCE" in
		cpuinfo) SERIAL=$(grep Serial /proc/cpuinfo | cut -d':' -f2) ;;
		random)  SERIAL=$(cat /proc/sys/kernel/random/uuid | tr -d '-') ;;
		*)       SERIAL="$USB_SERIAL_SOURCE" ;;
	esac
	echo ${SERIAL:-0123456789ABCDEF} > $USB_GADGET_STRINGS_DIR/serialnumber
	echo "$USB_MANUFACTURER" > $USB_GADGET_STRINGS_DIR/manufacturer
	echo "$USB_PRODUCT_NAME" > $USB_GADGET_STRINGS_DIR/product

	mkdir -p $USB_CONFIGS_DIR
	echo $USB_MAX_POWER > $USB_CONFIGS_DIR/MaxPower

	echo 0x1 > os_desc/b_vendor_code
	echo MSFT100 > os_desc/qw_sign
	ln -s $USB_CONFIGS_DIR os_desc/

	mkdir -p $USB_CONFIGS_STRINGS_DIR
}

usb_funcs_grep()
{
	echo $USB_FUNCS | xargs -n 1 | sort | uniq | grep $@ || true
}

usb_funcs_sort()
{
	{
		for func in $@; do
			usb_funcs_grep -E $func
		done
		usb_funcs_grep -vE $(echo $@ | tr ' ' '|')
	} | uniq | xargs
}

usb_prepare()
{
	usb_load_config

	# Allow function/variable overriding
	[ -d /etc/usbdevice.d ] && . /etc/usbdevice.d/*

	UMS_FILE=${UMS_FILE:-/userdata/ums_shared.img}
	UMS_SIZE=${UMS_SIZE:-256M}
	UMS_FSTYPE=${UMS_FSTYPE:-vfat}
	UMS_MOUNT=${UMS_MOUNT:-0}
	UMS_MOUNTPOINT="${UMS_MOUNTPOINT:-/mnt/ums}"
	UMS_RO=${UMS_RO:-0}
	USB_FUNCS=${USB_FUNCS:-adb}

	# Orders required by kernel
	USB_FUNCS="$(usb_funcs_sort rndis uac uvc adb ntb ums mtp acm)"
	USB_CONFIG="$(echo "$USB_FUNCS" | tr ' ' '_')"

	if [ ! -d $USB_GADGET_DIR ]; then
		mountpoint -q $CONFIGFS_DIR || \
			mount -t configfs none $CONFIGFS_DIR

		mkdir -p $USB_GADGET_DIR
		cd $USB_GADGET_DIR

		# Global initialize
		usb_run_stage usb init
	fi

	USB_STATE=$(cat /sys/class/android_usb/android0/state 2>/dev/null || echo "DISCONNECTED")
	USB_UDC=$(ls /sys/class/udc/ | head -n 1)

	# Parse started USB functions
	OLD_FUNCS=$(usb_get_started)
	USB_CURRENT_UDC="$(cat $USB_GADGET_DIR/UDC 2>/dev/null)"

	usb_msg "[DEBUG prepare] USB_STATE=$USB_STATE USB_UDC=$USB_UDC USB_FUNCS=$USB_FUNCS OLD_FUNCS=$OLD_FUNCS UDC=$USB_CURRENT_UDC"

	# Stop old USB functions when:
	# 1. Functions changed (normal reconfiguration)
	# 2. UDC unexpectedly unbound while functions still set (disconnect recovery)
	#    This kills the old daemon (e.g. adbd) whose FFS handles are now stale,
	#    clears the started state, and allows a fresh restart.
	if [ -n "$OLD_FUNCS" ]; then
		if [ "$OLD_FUNCS" != "$USB_FUNCS" ]; then
			usb_msg "Functions changed $OLD_FUNCS -> $USB_FUNCS"
			usb_stop
		elif [ -z "$USB_CURRENT_UDC" ]; then
			# Disconnect recovery: only kill daemons and clear started
			# state. Do NOT call usb_stop — it removes ConfigFS symlinks
			# which triggers functionfs_unbind and permanently breaks
			# FFS (private_data set to NULL, ffs_ready returns -EINVAL).
			usb_msg "UDC unbound, restarting daemons (preserving ConfigFS)"
			for func in $USB_FUNCS; do
				for instance in $(usb_instances $func); do
					cd $USB_FUNCTIONS_DIR/$instance &>/dev/null || continue
					usb_run_stage $func stop
				done
			done
			echo > $USB_FUNCS_FILE
			unset OLD_FUNCS
		fi
	fi

	# Update USB PID only when UDC is not bound (i.e. gadget is not active).
	# Writing idProduct while the UDC is bound triggers a gadget soft-
	# disconnect and re-enumeration, which — combined with the udev rule
	# that fires "usbdevice update" on every android_usb state change —
	# creates an infinite reset loop.
	if [ -z "$USB_CURRENT_UDC" ]; then
		usb_msg "[DEBUG prepare] UDC not bound, writing idProduct=$(usb_pid)"
		usb_pid > $USB_GADGET_DIR/idProduct
	else
		usb_msg "[DEBUG prepare] UDC bound ($USB_CURRENT_UDC), skipping idProduct write"
	fi
}

usb_start()
{
	# If the gadget is already running with the same functions, skip.
	# The udev rule fires "usbdevice update" on every android_usb state
	# change (CONNECTED/CONFIGURED/DISCONNECTED).  Re-running prepare
	# stages or touching ConfigFS attributes while the UDC is bound can
	# cause a soft-disconnect and an infinite reset loop.
	USB_CURRENT_UDC="$(cat $USB_GADGET_DIR/UDC 2>/dev/null)"
	STARTED_FUNCS="$(usb_get_started)"
	usb_msg "[DEBUG start] USB_CURRENT_UDC=$USB_CURRENT_UDC STARTED_FUNCS=$STARTED_FUNCS USB_FUNCS=$USB_FUNCS"
	if [ -n "$USB_CURRENT_UDC" ] && [ "$STARTED_FUNCS" = "$USB_FUNCS" ]; then
		usb_msg "[DEBUG start] Already running, skipping"
		return 0
	fi

	usb_msg "Starting functions: $USB_FUNCS"

	echo "$USB_CONFIG" > $USB_CONFIGS_STRINGS_DIR/configuration

	for func in $USB_FUNCS; do
		for instance in $(usb_instances $func); do
			usb_msg "Preparing instance: $instance"

			if ! mkdir -p $USB_FUNCTIONS_DIR/$instance 2>/dev/null; then
				usb_msg "Failed to create instance: $instance"
				continue
			fi

			cd $USB_FUNCTIONS_DIR/$instance &>/dev/null || continue

			usb_run_stage $func prepare

			# Make symlink after prepared (required by UVC)
			usb_symlink $USB_FUNCTIONS_DIR/$instance \
				$USB_CONFIGS_DIR/f-$instance
		done
	done

	usb_msg "[DEBUG start] Writing UDC=$USB_UDC"
	usb_write $USB_GADGET_DIR/UDC $USB_UDC

	# Verify UDC bind 真的成功。背景：写 sysfs UDC attr 时 echo 的退出码
	# 不一定反映 kernel 端写失败（stdio 缓冲 + sh builtin echo 差异）；
	# 当底层 dwc3 controller 还没 ready（典型场景：Rockchip RK3588 上
	# fusb302 USB-C PD 协商未完成），kernel 端 `udc_bind_to_driver` 返回
	# -ENODEV，echo 可能仍报 0。读回 sysfs 文件即可断言——成功 bind 时
	# 文件内容等于 $USB_UDC，失败时保持空。失败时 exit 1 让 systemd
	# Restart=on-failure 自动重试（service unit 已配，2 秒后 cold restart，
	# 那时 fusb302 通常已完成协商）；继续走 stale state 反而导致脏 daemon
	# 残留 + udev event 再触发 stop+start 循环，更糟。
	ACTUAL_UDC="$(cat $USB_GADGET_DIR/UDC 2>/dev/null || true)"
	if [ "$ACTUAL_UDC" != "$USB_UDC" ]; then
		usb_msg "[ERROR] UDC bind 失败：expected=$USB_UDC actual='$ACTUAL_UDC' —— 底层 controller 未 ready（dwc3/fusb302 PD 协商未完成？）。退出 1 触发 systemd Restart=on-failure。"
		exit 1
	fi

	for func in $USB_FUNCS; do
		for instance in $(usb_instances $func); do
			cd $USB_FUNCTIONS_DIR/$instance &>/dev/null || continue

			usb_msg "Starting instance: $instance"
			usb_run_stage $func start
		done
	done

	# 校验主机真的枚举成功 —— 仅 readback UDC 只能确认 gadget 已 bind，
	# 确认不了枚举。QCS6490 实测：开机首次 bind 后主机枚举撞 dwc3 ep0
	# 竞态（dmesg "request was not queued to ep0out"），UDC state 卡在非
	# configured、adb 上不来，必须手动 systemctl restart。这里把"手动
	# restart"自动化：bind 后总是做一次 soft_connect bounce（等同 restart
	# 的干净重新枚举，adbd/FFS 此时已 ready；无主机时翻转 pullup 也无副作用），
	# 再校验 state==configured。仍卡住且确有主机连接时 exit 1，交给 systemd
	# Restart=on-failure 冷重试（StartLimitBurst 兜底）。
	usb_bounce_connection || true
	if usb_wait_state configured 30; then
		usb_msg "[DEBUG start] 枚举成功：state=configured"
	else
		ENUM_STATE="$(cat /sys/class/udc/$USB_UDC/state 2>/dev/null || echo unknown)"
		if [ "$ENUM_STATE" = "not attached" ]; then
			# 无 VBUS / 未接主机，属正常；保持 gadget bind，插线即枚举。
			usb_msg "[DEBUG start] 无主机连接 (state=$ENUM_STATE)，保持 bind"
		else
			usb_msg "[ERROR] 枚举失败 (state=$ENUM_STATE)：底层 ep0/枚举竞态未恢复。退出 1 触发 systemd Restart=on-failure。"
			exit 1
		fi
	fi

	# Store started functions
	usb_set_started
}

usb_stop()
{
	if [ -n "$OLD_FUNCS" ]; then
		usb_msg "[DEBUG stop] Stopping functions: $OLD_FUNCS"
	fi

	usb_msg "[DEBUG stop] Unbinding UDC"
	usb_write $USB_GADGET_DIR/UDC ""

	for func in $USB_FUNCS; do
		for instance in $(usb_instances $func); do
			cd $USB_FUNCTIONS_DIR/$instance &>/dev/null || continue

			usb_msg "Stopping instance: $instance"
			usb_run_stage $func stop
		done
	done

	rm -f $USB_CONFIGS_DIR/f-*

	# Clear started state so usb_start_daemon will relaunch daemons
	echo > $USB_FUNCS_FILE

	# Clear functions to avoid stopping them again
	unset OLD_FUNCS
}

usb_restart()
{
	usb_run_stage usb stop
	usb_run_stage usb start
}

ACTION=${1:-update}
if [ "$ACTION" = update ]; then
	usb_is_enabled || exit 0
fi

# Lock it
exec 3<$0
flock -x 3

echo "Starting $0 ${ACTION}, log saved to $LOG_FILE"

# Redirect outputs to log file
exec >>$LOG_FILE 2>&1

usb_msg "=== Handling ${ACTION} request (PID=$$) ==="

usb_run_stage usb prepare

case "$ACTION" in
	start|update)
		usb_enable
		usb_run_stage usb start
		;;
	stop)
		usb_disable
		usb_run_stage usb stop
		;;
	restart)
		usb_enable
		usb_run_stage usb restart
		;;
	*)
		echo "Usage: usbdevice [start|stop|restart|update]" >&2
		;;
esac

usb_msg "Done $ACTION request"
echo

# Unlock it
flock -u 3
