app:
  name: flange-ubuntu-desktop-config
  version: 1.0.1
  description: Ubuntu Desktop Dock、Remote Login 与 Snap 应用配置
  type: service
  arch: [aarch64]

maintainer:
  name: flange
  email: flange@localhost

build:
  system: none

install:
  schemas/99_flange-ubuntu-dock.gschema.override: /usr/share/glib-2.0/schemas/99_flange-ubuntu-dock.gschema.override

systemd:
  unit: systemd/flange-configure-ubuntu-desktop.service
  auto_start: true

depends:
  - ubuntu-desktop
  - glmark2-wayland
  - language-pack-zh-hans
  - language-pack-gnome-zh-hans
  - fonts-noto-cjk
  - gnome-remote-desktop
  - chromium-browser
  - snapd
  - openssl

data_dirs: []
