app:
  name: rkmm-gst-repack
  version: 1.0.0
  description: 按 Ubuntu Noble 分包边界重打 GStreamer runtime deb
  type: vendor
  arch: [aarch64]

maintainer:
  name: flange
  email: flange@localhost

build:
  system: custom
  commands:
    - [python3, ../../lib/unit.py, rkmm-gst-repack]
  deps:
    - rkmm-gstreamer
    - rkmm-gst-base
    - rkmm-gst-good
    - rkmm-gst-bad
  apt_packages:
    - bison
    - cmake
    - dpkg-dev
    - flex
    - git
    - iso-codes
    - libasound2-dev:{arch}
    - libcairo2-dev:{arch}
    - libcdparanoia-dev:{arch}
    - libdrm-dev:{arch}
    - libegl-dev:{arch}
    - libflac-dev:{arch}
    - libgbm-dev:{arch}
    - libgl-dev:{arch}
    - libgles-dev:{arch}
    - libglib2.0-dev:{arch}
    - libgraphene-1.0-dev:{arch}
    - libgudev-1.0-dev:{arch}
    - libjpeg-dev:{arch}
    - libjson-glib-dev:{arch}
    - libnice-dev:{arch}
    - libogg-dev:{arch}
    - libopus-dev:{arch}
    - liborc-0.4-dev:{arch}
    - libpango1.0-dev:{arch}
    - libpng-dev:{arch}
    - libpulse-dev:{arch}
    - libsoup-3.0-dev:{arch}
    - libsrtp2-dev:{arch}
    - libssl-dev:{arch}
    - libtheora-dev:{arch}
    - libvisual-0.4-dev:{arch}
    - libvorbis-dev:{arch}
    - libv4l-dev:{arch}
    - libwayland-dev:{arch}
    - libx11-dev:{arch}
    - libxext-dev:{arch}
    - libxml2-dev:{arch}
    - libxv-dev:{arch}
    - meson
    - nasm
    - ninja-build
    - patch
    - wayland-protocols
    - xz-utils
  deb_outputs:
    - libgstreamer1.0-0_1.24.2-1ubuntu0.1+flange1_arm64.deb
    - gstreamer1.0-tools_1.24.2-1ubuntu0.1+flange1_arm64.deb
    - gstreamer1.0-plugins-base-apps_1.24.2-1ubuntu0.4+flange1_arm64.deb
    - libgstreamer-plugins-base1.0-0_1.24.2-1ubuntu0.4+flange1_arm64.deb
    - libgstreamer-gl1.0-0_1.24.2-1ubuntu0.4+flange1_arm64.deb
    - gstreamer1.0-alsa_1.24.2-1ubuntu0.4+flange1_arm64.deb
    - gstreamer1.0-plugins-base_1.24.2-1ubuntu0.4+flange1_arm64.deb
    - gstreamer1.0-x_1.24.2-1ubuntu0.4+flange1_arm64.deb
    - gstreamer1.0-gl_1.24.2-1ubuntu0.4+flange1_arm64.deb
    - gstreamer1.0-plugins-good_1.24.2-1ubuntu1.5+flange1_arm64.deb
    - libgstreamer-plugins-good1.0-0_1.24.2-1ubuntu1.5+flange1_arm64.deb
    - gstreamer1.0-plugins-bad-apps_1.24.2-1ubuntu4+flange1_arm64.deb
    - gstreamer1.0-plugins-bad_1.24.2-1ubuntu4+flange1_arm64.deb
    - libgstreamer-plugins-bad1.0-0_1.24.2-1ubuntu4+flange1_arm64.deb
