load(":cc_toolchain_config.bzl", "cc_toolchain_config")

# aarch64 交叉编译工具链配置
cc_toolchain_config(
    name = "aarch64_linux_config",
)

# 空 filegroup，toolchain 文件由系统提供
filegroup(
    name = "empty",
    srcs = [],
)

cc_toolchain(
    name = "aarch64_linux_cc_toolchain",
    all_files = ":empty",
    compiler_files = ":empty",
    dwp_files = ":empty",
    linker_files = ":empty",
    objcopy_files = ":empty",
    strip_files = ":empty",
    toolchain_config = ":aarch64_linux_config",
)

toolchain(
    name = "aarch64_linux_toolchain",
    exec_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    target_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:aarch64",
    ],
    toolchain = ":aarch64_linux_cc_toolchain",
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
)

# aarch64 linux 目标平台
platform(
    name = "aarch64_linux",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:aarch64",
    ],
)
